--- #YAML:1.0
name: Apache2::WebApp::Plugin::Cookie
abstract: Common methods for creating and manipulating web browser cookies.
version: 0.04
author:
  - Marc S. Brooks <mbrooks@cpan.org>
license: perl and artistic
distribution_type: module
requires:
  Apache2::WebApp: 0.01
  Apache2::WebApp::Plugin::Filters: 0.01
  Params::Validate: 0
build_requires:
  Apache::Test: 0
  Apache2::WebApp::Plugin::CGI: 0.01
resources:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
